### ISSUE TITLE
Replacement method doesn't work for concatenated files

### ISSUE THREAD

**Issue by mfernea** [ferares/gulp-remove-sourcemaps#1]
I'm using gulp-include and my script file contains:
```
//=require component1/component1.min.js
//=require component2/component2.min.js

... my code;
```
My problem is that those min.js files contain sourcemaps declarations. When using the gulp-remove-sourcemaps my code gets deleted as the plugin removes everything after sourcemaps declaration, which is fine only for single files, not for concatenated ones. 

Something like this would work:
```
    const regex = /\/\/# sourceMappingURL=.*/g;
    contents = contents.replace(regex, '')
```

**Comment by ferares** [comment]
Hi @mfernea, thanks for providing the fix, do you want to create a PR or should I just send a push?

**Comment by mfernea** [comment]
Since it's just a small change, please send a push.

**Comment by ferares** [comment]
A little late but here it is e1580dd30450dd8fe6f6a5439562bcc59c26dfc6 😅
