### ISSUE TITLE
Regex is not so global

### ISSUE THREAD

**Issue by fklee** [ferares/gulp-remove-sourcemaps#2]
Hello,

Just try, THE plugin I was looking for !! 
But your regex does not complete as my map infos are written :
This one complete the job : `    const regex = /\# sourceMappingURL=.* /g;` As it only leave the comment from the original line : `/*# sourceMappingURL=style-mail.css.map */`

**Comment by ferares** [comment]
You're right except that that regex does not capture the whole line so it would leave behind the opening `/*` I think the correct regex would be `/.*# sourceMappingURL=.*/g` I'll do some testing and push the change shortly

**Comment by ferares** [comment]
All done, thank you for the feedback 2eb044f97636ceb87a77b1892df505b6b5f29fa6
