### ISSUE TITLE
Remove alternate sourcemap reference syntax

### ISSUE THREAD

**Issue by jamesfredleyallied** [ferares/gulp-remove-sourcemaps#3]
In Chrome, the following alternate syntax is a valid reference and the source map file is requested in dev tools.

/*# sourceMappingURL=sourcemaps/tiny-slider.css.map */

This alternate syntax is not currently removed by gulp-remove-sourcemaps.  Would you consider adding it?

https://www.npmjs.com/package/tiny-slider

**Comment by ferares** [comment]
oops, that was already covered by a previous update but forgot to do `npm publish` you can update to version 1.0.2 now and it should work for that syntax too.
